module.exports = Object.freeze({
    MONGODB: {
        URL: 'mongodb://localhost:27017/etmPayroll?retryWrites=false',
    },
    SERVER: {
        HOSTNAME: 'localhost',
        PORT: '3000'
    },
    OAUTH: {
        ALLOWED_GRANTS: ["password", "refresh_token"],
        ACCESS_TOKEN_LIFETIME: 604800,//in seconds
        REFRESH_TOKEN_LIFETIME: 1209600,// in seconds
    },
    AWS: {
        ENDPOINT: 'http://localhost:4002',
        ACCESS_KEY_ID: 'S3RVER',
        SECRET_ACCESS_KEY: 'S3RVER',
        REGION: 'ap-south-1',
        URL: 'http://localhost:4002/etmpayroll-bucket/'
    },
    MAIL: {
        ENABLE: true,
        SERVICE: 'gmail',
        EMAIL: 'eliran.natan@outlook.com',
        PASSWORD: 'eliran@12345',
        FROM: 'ETM-Payroll<eliran.natan@outlook.com>'
    },
    API: {
        DEFAULT_STATUS_CODE: 200,
        SUCCESS_CODE: 1,
        FAIL_CODE: 0,
        OAUTH_FAIL_CODE: 2
    },
    UTILS: {
        DATETIME_FORMAT: 'YYYY-MM-DD HH:mm:ss',// not in use
        RESEND_OTP_TIME: 30,
        DEFAULT_USER_IMG: 'default_user.jpeg',
        DEFAULT_EMPLOYEE_IMG: 'default_employee.jpeg',
    },
    STATUS: {
        ACTIVE: 'active',
        INACTIVE: 'inactive',
        EXPIRED: 'expired',
        DELETED: 'deleted',
        APPROVED: 'approved',
        PENDING: 'pending',
        REJECTED: 'rejected',
    },
    OPERATION_TYPE: {
        VIEW: 'view',
        CREATE: 'create',
        UPDATE: 'update',
        DELETE: 'delete',
    },
    LEVEL: {
        DEBUG: 'debug',
        INFO: 'info',
        WARN: 'warn',
        ERROR: 'error',
        FATAL: 'fatal',
    },
    MODULE: {
        ADD_ADMIN: 'add_admin',
        ADD_COMPANY: 'add_company',
        EDIT_COMPANY: 'edit_company',
        DELETE_COMPANY: 'delete_company',
        PERMISSION_LIST: 'permission_list',
        ADD_PERMISSION: 'add_permission',
        ADD_MULTIPLE_PERMISSION: 'add_multiple_permission',
        EDIT_PERMISSION: 'edit_permission',
        DELETE_PERMISSION: 'delete_permission',
        ROLE_LIST: 'role_list',
        ADD_ROLE: 'add_role',
        EDIT_ROLE: 'edit_role',
        DELETE_ROLE: 'delete_role',
        ADD_USER: 'add_user',
        EDIT_USER: 'edit_user',
        DELETE_USER: 'delete_user',
        VERIFY_OTP: 'verify_otp',
        UPDATE_PROFILE_PIC: 'update_profile_pic',
        DELETE_PROFILE_PIC: 'delete_profile_pic',
        FORGOT_PASSWORD: 'forgot_password',
        COMPANY_LIST: 'company_list',
        COMPANY_DETAIL: 'company_detail',
        USER_LIST: 'user_list',
        MASTER_LEAVE_LIST: 'master_leave_list',
        ADD_MASTER_LEAVE: 'add_master_leave',
        EDIT_MASTER_LEAVE: 'edit_master_leave',
        DELETE_MASTER_LEAVE: 'delete_master_leave',
        MASTER_SALARY_LIST: 'master_salary_list',
        ADD_MASTER_SALARY: 'add_master_salary',
        EDIT_MASTER_SALARY: 'edit_master_salary',
        DELETE_MASTER_SALARY: 'delete_master_salary',
        LOG_LIST: 'log_list',
        COMPANY_LEAVE_LIST: 'company_leave_list',
        ADD_COMPANY_LEAVE: 'add_company_leave',
        EDIT_COMPANY_LEAVE: 'edit_company_leave',
        DELETE_COMPANY_LEAVE: 'delete_company_leave',
        COMPANY_SALARY_LIST: 'company_salary_list',
        ADD_COMPANY_SALARY: 'add_company_salary',
        EDIT_COMPANY_SALARY: 'edit_company_salary',
        DELETE_COMPANY_SALARY: 'delete_company_salary',
        EMPLOYEE_LEAVE_HISTORY: 'employee_leave_history',
        REQUEST_LEAVE: 'request_leave',
        EDIT_REQUEST_LEAVE: 'edit_request_leave',
        DELETE_REQUEST_LEAVE: 'delete_request_leave',
        USER_LEAVE: 'user_leave',
        APPROVE_REJECT_LEAVE_REQUEST: 'approve_reject_leave',
        HOLIDAY_LIST: 'holiday_list',
        ADD_HOLIDAY: 'add_holiday',
        EDIT_HOLIDAY: 'edit_holiday',
        DELETE_HOLIDAY: 'delete_holiday',
        BANK_ACCOUNT_LIST: 'bank_account_list',
        ADD_BANK_ACCOUNT: 'add_bank_account',
        EDIT_BANK_ACCOUNT: 'edit_bank_account',
        DELETE_BANK_ACCOUNT: 'delete_bank_account',
        UPDATE_CHECK_IMG: 'update_check_img',
        DELETE_CHECK_IMG: 'delete_check_img',
        PAYROLL_LIST: 'payroll_list',
        ADD_PAYROLL: 'add_payroll',
        EDIT_PAYROLL: 'edit_payroll',
        DELETE_PAYROLL: 'delete_payroll',
        APPRAISAL_LIST: 'appraisal_list',
        ADD_APPRAISAL: 'add_appraisal',
        EDIT_APPRAISAL: 'edit_appraisal',
        DELETE_APPRAISAL: 'delete_appraisal',
        EMPLOYEE_LIST: 'employee_list',
        ADD_EMPLOYEE: 'add_employee',
        EDIT_EMPLOYEE: 'edit_employee',
        DELETE_EMPLOYEE: 'delete_employee',
      
    },
    ROUTES: {
        LOGIN: '/login',
        REFRESH_TOKEN: '/refresh_token',
        ADD_ADMIN: '/add_admin',
        ADD_COMPANY: '/add_company',
        EDIT_COMPANY: '/edit_company/:id',
        DELETE_COMPANY: '/delete_company',
        ROLE_LIST: '/role_list',
        ADD_ROLE: '/add_role',
        EDIT_ROLE: '/edit_role',
        DELETE_ROLE: '/delete_role',
        ADD_USER: '/add_user',
        EDIT_USER: '/edit_user',
        DELETE_USER: '/delete_user',
        FORGOT_PASSWORD: '/forgot_password',
        VERIFY_OTP: '/verify_otp',
        UPDATE_PROFILE_PIC: '/update_profile_pic',
        DELETE_PROFILE_PIC: '/delete_profile_pic',
        PERMISSION_LIST: '/permission_list',
        ADD_PERMISSION: '/add_permission',
        ADD_MULTIPLE_PERMISSION: '/add_multiple_permission',
        EDIT_PERMISSION: '/edit_permission',
        DELETE_PERMISSION: '/delete_permission',
        COMPANY_LIST: '/company_list',
        USER_LIST: '/user_list',
        MASTER_LEAVE_LIST: '/master_leave_list',
        ADD_MASTER_LEAVE: '/add_master_leave',
        EDIT_MASTER_LEAVE: '/edit_master_leave',
        DELETE_MASTER_LEAVE: '/delete_master_leave',
        MASTER_SALARY_LIST: '/master_salary_list',
        ADD_MASTER_SALARY: '/add_master_salary',
        EDIT_MASTER_SALARY: '/edit_master_salary',
        DELETE_MASTER_SALARY: '/delete_master_salary',
        LOG_LIST: '/log_list',
        COMPANY_LEAVE_LIST: '/company_leave_list',
        ADD_COMPANY_LEAVE: '/add_company_leave',
        EDIT_COMPANY_LEAVE: '/edit_company_leave',
        DELETE_COMPANY_LEAVE: '/delete_company_leave',
        COMPANY_SALARY_LIST: '/company_salary_list',
        ADD_COMPANY_SALARY: '/add_company_salary',
        EDIT_COMPANY_SALARY: '/edit_company_salary',
        DELETE_COMPANY_SALARY: '/delete_company_salary',
        EMPLOYEE_LEAVE_HISTORY: '/employee_leave_history',
        REQUEST_LEAVE: '/request_leave',
        EDIT_REQUEST_LEAVE: '/edit_request_leave',
        DELETE_REQUEST_LEAVE: '/delete_request_leave',
        USER_LEAVE: '/user_leave',
        APPROVE_REJECT_LEAVE_REQUEST: '/approve_reject_leave',
        HOLIDAY_LIST: '/holiday_list',
        ADD_HOLIDAY: '/add_holiday',
        EDIT_HOLIDAY: '/edit_holiday',
        DELETE_HOLIDAY: '/delete_holiday',
        BANK_ACCOUNT_LIST: '/bank_account_list',
        ADD_BANK_ACCOUNT: '/add_bank_account',
        EDIT_BANK_ACCOUNT: '/edit_bank_account',
        DELETE_BANK_ACCOUNT: '/delete_bank_account',
        UPDATE_CHECK_IMG: '/update_check_img',
        DELETE_CHECK_IMG: '/delete_check_img',
        PAYROLL_LIST: '/payroll_list',
        ADD_PAYROLL: '/add_payroll',
        EDIT_PAYROLL: '/edit_payroll',
        DELETE_PAYROLL: '/delete_payroll',
        APPRAISAL_LIST: '/appraisal_list',
        ADD_APPRAISAL: '/add_appraisal',
        EDIT_APPRAISAL: '/edit_appraisal',
        DELETE_APPRAISAL: '/delete_appraisal',
        UPLOAD:"/upload",
        EMPLOYEE_LIST: '/employee_list',
        ADD_EMPLOYEE: '/add_employee',
        EDIT_EMPLOYEE: '/edit_employee',
        DELETE_EMPLOYEE: '/delete_employee',
    },
});