service: etmpayrollapi

frameworkVersion: '2 || 3'

plugins:
  - serverless-s3-local
  - serverless-offline

provider:
  name: aws
  runtime: nodejs12.x
  environment:
    S3_BucketName: etmpayroll-bucket
  region: ap-south-1
  lambdaHashingVersion: 20201221

custom:
  s3:
    host: 0.0.0.0
    port: 4002
    directory: C:\Users\bhavi\OneDrive\Desktop\etmpayrollapi

resources:
  Resources:
    NewResource:
      Type: AWS::S3::Bucket
      # Properties:
      #   BucketName: etmpayroll-bucket


functions:
	
  app:
    handler: index.handler
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'

